name: release-artifact

on:
  push:
    tags:
      - '**'

jobs:
  flux-push-component:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # for pushing
      id-token: write # for signing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flux
        uses: controlplaneio-fluxcd/distribution/actions/setup@main
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare tags
        id: prep
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ $REF_NAME != */* ]]; then
              echo "Ref name is not in the format component/version"
              exit 1
          fi
          
          COMPONENT=$(echo "$REF_NAME" | cut -d'/' -f 1)
          VERSION=$(echo "$REF_NAME" | cut -d'/' -f 2)
          
          echo "component=${COMPONENT}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Push artifact
        uses: controlplaneio-fluxcd/distribution/actions/push@main
        id: push
        with:
          repository: ghcr.io/${{ github.repository }}/${{ steps.prep.outputs.component }}
          path: "./components/${{ steps.prep.outputs.component }}"
          diff-tag: ${{ steps.prep.outputs.version }}
          tags: latest-stable
      - name: Sign artifact
        if: steps.push.outputs.pushed == 'true'
        run: cosign sign --yes $DIGEST_URL
        env:
          DIGEST_URL: ${{ steps.push.outputs.digest-url }}
